Name=input("Enter your name:")
Age=int(input("Enter your age:"))
Course=input("Enter course:")
College=input("Enter college name:")
Email=input("Enter your email:")
print(" Student Bio Card")
print(f" || Name:{Name}     ||")
print(f" || Age:{Age}       ||")
print(f" || Course:{Course} ||")
print(f" || College:{College}||")
print(f" || Email:{Email}    ||")
